[toolchain]
arch = "aarch64"
host = "${PKGS_ARCH}-none-elf"
bin = "${PKGS_ROOT}/some/toolchain/path/bin"
cross_prefix = "${PKGS_HOST}-"
extra_programs = [
    "autoconf",
    "libtool",
    "pkg-config",
]

[[packages]]
name = "zlib"
url = "https://zlib.net/zlib-1.3.1.tar.gz"
build = """
./configure --prefix=/usr --static
make AR="$AR rc" ARFLAGS=""
"""
install = """
make install DESTDIR=$INSTALL_ROOT AR="$AR rc" ARFLAGS=""
"""

[[packages]]
name = "file"
url = "http://ftp.astron.com/pub/file/file-5.45.tar.gz"
build = """
./configure --prefix=/usr --host=x86_64-linux-musl --enable-static --disable-shared --disable-libseccomp
touch aclocal.m4 configure Makefile.in src/Makefile.in magic/Makefile.in config.h.in
make -C src magic.h libmagic.la
make -C src file LDFLAGS="-all-static"
"""
install = """
make -C src install DESTDIR=$INSTALL_ROOT
"""

[[packages]]
name = "curl"
url = "https://curl.se/download/curl-8.5.0.tar.gz"
build = """
./configure --host=x86_64-linux-musl --prefix=/usr --enable-static --disable-shared --with-zlib \
  --without-ssl --without-libpsl --without-libidn2 --disable-ldap --disable-rtsp --disable-manual
make curl_LDFLAGS="-all-static"
"""
install = """
make install DESTDIR=$INSTALL_ROOT
"""
depends_on = ["zlib"]
